version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "yjc"
      RABBITMQ_DEFAULT_PASS: "yjc666"
    ports:
      - "15672:15672"
    networks:
      - oss-network

  elastic:
    image: elasticsearch:7.6.2
    container_name: elastic
    hostname: elastic
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - oss-network

  api-server:
    build:  
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    restart: always
    environment:
      LISTEN_ADDRESS: "0.0.0.0:30000"
      RABBITMQ_SERVER: "amqp://test:test@rabbitmq:5672"
      ES_SERVER: "elastic:9200"
    command:      
      - /bin/bash 
      - -c 
      - |
        cd /go/src/go-oss/apiServer
        go run *.go
    ports:
      - "30000:30000"
    networks:
      - oss-network
        
  data-server-1:
    build:  
      context: .
      dockerfile: Dockerfile
    container_name: data-server-1
    hostname: data-server-1
    restart: always
    environment:
      LISTEN_ADDRESS: "data-server-1:20000"
      RABBITMQ_SERVER: "amqp://test:test@rabbitmq:5672"
      STORAGE_ROOT: "/storage"
    volumes:
      - ./storage/1/objects:/storage/objects
      - ./storage/1/temp:/storage/temp
    command: 
      - /bin/bash 
      - -c 
      - |
        cd /go/src/go-oss/dataServer 
        go run dataServer.go
    networks:
      - oss-network

  data-server-2:
    build:  
      context: .
      dockerfile: Dockerfile
    container_name: data-server-2
    hostname: data-server-2
    restart: always
    environment:
      LISTEN_ADDRESS: "data-server-2:20000"
      RABBITMQ_SERVER: "amqp://test:test@rabbitmq:5672"
      STORAGE_ROOT: "/storage"
    volumes:
      - ./storage/2/objects:/storage/objects
      - ./storage/2/temp:/storage/temp
    command: 
      - /bin/bash 
      - -c 
      - |
        cd /go/src/go-oss/dataServer 
        go run dataServer.go
    networks:
      - oss-network

networks:
  oss-network:
    driver: bridge